### ISSUE TITLE
QueuedJob query using 'Implementation' column without index

### ISSUE THREAD

**Issue by brettt89** [silverstripe/silverstripe-contentreview#143]
The SiteTree extension, when calling 'default records' function, queries the QueuedJobDescriptor table for a ContentReviewJob. However it is doing so using the `Implementation` column which does not have any index associated.

https://github.com/silverstripe/silverstripe-contentreview/blob/4/src/Extensions/SiteTreeContentReview.php#L666

As the `QueuedJobDescsriptor.Implementation` column is a `varchar(255)`, it is having to do a full-scan on the table when searching, this takes quite a while to perform and gets exponentially worse with the more records in this table.

E.g. A `QueuedJobDescriptor` table with 180k records takes over 1 minute to run this single query.

**Comment by Cheddam** [comment]
Thanks for raising this @brettt89! Unfortunately this isn't really an issue with the Content Review module, and it's certainly not _solvable_ by this module (short of applying an extension to the QueuedJobDescriptor model to patch in an index, which definitely feels like the wrong approach.)

Since [an issue addressing this](https://github.com/symbiote/silverstripe-queuedjobs/issues/336) has also been raised about this on the Queued Jobs module, I think we'll close this one out in favour of tackling the resolution there.
